import ProductPage from "@/component/home/ProductPage";
import React from "react";
export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};
const ProductItems = () => {
  return (
    <div>
      <ProductPage />
    </div>
  );
};

export default ProductItems;
